[valores_CN]
#ANICONS = "https://i.imgur.com/A2pPOED.png"
SNOWY = "https://i.imgur.com/KxcqKpJ.gif"
SNOW = "https://i.imgur.com/mpOU7Ca.gif"
HSNOW = "https://i.imgur.com/i5dLK8G.gif"
BSNOW = "https://i.imgur.com/4B1xuMw.gif"
SUICONS = "https://i.imgur.com/cM95ybG.jpg"
ANICONS = "https://i.imgur.com/bmUoCIb.png"
SUPPLY = "https://i.imgur.com/PWreEK2.gif"
PARADRP = "https://i.imgur.com/ShQMIoU.png"
LAND = "https://i.imgur.com/Cmyq9vd.jpg"
[folha_CN]
ANICONS = [4, 4]
SUICONS = [8, 4]

[r_ROOT]
img="https://i.imgur.com/Cmyq9vd.jpg"
index=0

[r_ROOT.e_ping]
img="https://i.imgur.com/bmUoCIb.png"
#img=".i.ANICONS.1"
x=700
y=300
w=64
h=64
o=0.2
index=1
b=1
texto="Me parece um animal distante"