[valores_CN]
#ANICONS = "https://i.imgur.com/A2pPOED.png"
SNOWY = "https://i.imgur.com/KxcqKpJ.gif"
SNOW = "https://i.imgur.com/mpOU7Ca.gif"
HSNOW = "https://i.imgur.com/i5dLK8G.gif"
BSNOW = "https://i.imgur.com/4B1xuMw.gif"
SUICONS = "https://i.imgur.com/cM95ybG.jpg"
ANICONS = "https://i.imgur.com/bmUoCIb.png"
SUPPLY = "https://i.imgur.com/PWreEK2.gif"
PARADRP = "https://i.imgur.com/ShQMIoU.png"
LAND = "https://i.imgur.com/Cmyq9vd.jpg"
LANDER = "https://i.imgur.com/lc5s0OJ.jpg"
YELLOW = "https://imgur.com/dzM9NtT.jpg"
WHITE = "https://imgur.com/khohhCw.jpg"
RED = "https://imgur.com/IMcwSAq.jpg"
[folha_CN]
ANICONS = [5, 4]
SUICONS = [8, 4]
LAND = [4,8]
LANDER = [8,8]
YELLOW = [8,16]
#CROW = [1,1]
[valores_Missao]
ANIMAL = "https://i.imgur.com/BivOv8y.jpg"
AVENTURA = "https://imgur.com/CqlwpCh.jpg"
MISSAO = "https://imgur.com/aFuEYkS.jpg"
EVENTO = "https://imgur.com/qa5FFq3.jpg"
[folha_Missao]
ANIMAL = [3,1]
AVENTURA = [2,1]
MISSAO = [6,3]
EVENTO = [6,3]
[c_GEM]
img=".i.CN._LANDER.5"
[c_POOL]
img=".i.CN._LANDER.5"
e_mani.img=".i.Missao._MISSAO.1"
e_mani.x=100
e_mgeo.img=".i.Missao._MISSAO.2"
e_mgeo.x=200

[c_CROW]
img=".i.CN._LANDER.7"

c_RISCO.img=".i.CN._LANDER.9"

[c_CROW.e_tent]
img="*fa fa-campground fa-5x"
x=900
y=300
w=100
h=100
texto="Voltaremos ao campo base"
foi=".i.ROOT.0.0"

[c_ROOT]
#img="https://i.imgur.com/Cmyq9vd.jpg"
img=".i.CN._LANDER.1"

[c_ROOT.e_gem]
img="*fa fa-gem fa-5x"
x=900
y=300
w=100
h=100
texto="Talvez tenha um tesouro"
foi=".i.GEM.0.0"

[c_ROOT.e_crow]
img="*fa fa-crow fa-5x"
x=800
y=300
w=100
h=100
foi=".i.CROW.0.0"
texto="Me parece um pássaro distante"
[c_ROOT.e_ping]
#img="https://i.imgur.com/bmUoCIb.png"
img=".i.CN._ANICONS.1"
x=700
y=300
w=64
h=64
o=0.5
index=1
b=4
texto="Me parece um animal distante"

[s_ROOT]
img =".i.CN._LANDER.0"
index = [0,1,2,3]
[l_BIO]
img =".i.CN._LANDER.0"
index = [3,3]
[l_YEL]
img =".i.CN._YELLOW.0"
index = [6,5]

[s_Bioma]
img =".i.CN._LANDER.0"
index = [4,5,6,7]
[e_ave]
img="*fa fa-crow fa-5x"
x=700
y=300
texto="Parece um pássaro"
cena=".i.Biomazz5.0.0"
foi=".i.Biomazz7.0.0"
[e_gems]
img="*fa fa-box fa-5x"
x=900
y=300
texto="Talvez tenha um tesouro"
cena=".i.ROOTzz0.0.0"
foi=".i.GEM.0.0"
[e_supri]
img="*fa fa-parachute-box fa-5x"
x=900
y=300
texto="Os suprimentos cairam nesta direção"
cena=".i.ROOTzz1.0.0"
foi=".i.Biomazz4.0.0"
[e_base]
img="*fa fa-campground fa-5x"
x=900
y=300
texto="Voltaremos ao campo base"
cena=".i.Biomazz5.0.0"
foi=".i.ROOTzz0.0.0"
[e_lab]
img="*fa fa-arrows-to-circle fa-5x"
x=700
y=300
texto="A missão inicia aqui"
cena=".i.ROOTzz0.0.0"
foi=".i.BIOzz0zz0.0.0"
[e_ani]
img=".i.Missao._ANIMAL.0"
x=100
y=100
w=300
h=500
o=0.5
b=1
cena=".i.ROOTzz0.0.0"
texto="Lista de missões"
tit="Lista de missões"
foi=".i.POOL.0.0"
[e_adv]
img=".i.Missao._AVENTURA.0"
x=500
y=100
w=300
h=500
o=0.5
b=1
cena=".i.ROOTzz0.0.0"
texto="A missão inicia aqui"
tit="A missão inicia aqui"
foi=".i.BIOzz0zz1.0.0"
[e_adt]
img=".i.Missao._AVENTURA.1"
x=900
y=100
w=300
h=500
o=0.5
b=1
cena=".i.ROOTzz0.0.0"
texto="Outra missão inicia aqui"
tit="Outra missão inicia aqui"
foi=".i.YELzz0zz1.0.0"
